# -*- mode: python -*-

block_cipher = None

a = Analysis(
    [
        'gui.py',
        'release.py',
        'builder.py',
        'src/Assets.py',
        'src/Command.py',
        'src/DataJson.py',
        'src/JP.py',
        'src/Spoilers.py',
        'src/SpurningRibbon.py',
        'src/Bosses.py',
        'src/Image.py',
        'src/AbilitySP.py',
        'src/ProcessedSpecies.py',
        'src/PathActions.py',
        'src/Weapons.py',
        'src/AbilityWeapons.py',
        'src/AbilityPower.py',
        'src/DataTable.py',
        'src/EnemyGroups.py',
        'src/Shuffler.py',
        'src/SkipTutorials.py',
        'src/Randomizer.py',
        'src/JobStats.py',
        'src/Pak.py',
        'src/Guilds.py',
        'src/Databases/NPCDB.py',
        'src/Databases/SupportDB.py',
        # 'src/Databases/__init__.py',
        'src/Databases/EnemyDB.py',
        'src/Databases/ItemDB.py',
        'src/Databases/AbilitySetDB.py',
        'src/Databases/AbilityDB.py',
        'src/Databases/ObjectDB.py',
        'src/Databases/ReminiscenceSettings.py',
        'src/Databases/PCDB.py',
        'src/Databases/ShopDB.py',
        'src/Databases/ShopList.py',
        'src/Databases/NPCShopDB.py',
        'src/Databases/JobDB.py',
        'src/Databases/InvadeData.py',
        'src/Databases/EnemyGroupDB.py',
        'src/Databases/TextDB.py',
        'src/Databases/GuildDB.py',
        'src/Shields.py',
        'src/Events.py',
        'src/Softlocks.py',
        'src/Manager.py',
        'src/Treasures.py',
        'src/Support.py',
        'src/Battles.py',
        'src/Utility.py',
        'src/DataFile.py',
        'src/Nothing.py',
    ],
    pathex=[],
    binaries=[],
    datas=[
        ('json/*.json', 'json'),
        ('image/*.bin', 'image'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher,
    name='mybuild'
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='OT2R.exe',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console=False
)
